// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: backendservice/backend_service.proto

package backendservicepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_backendservice_backend_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_backendservice_backend_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_backendservice_backend_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// The response message containing the greetings
type ListAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllUsersResponse) Reset() {
	*x = ListAllUsersResponse{}
	mi := &file_backendservice_backend_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllUsersResponse) ProtoMessage() {}

func (x *ListAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backendservice_backend_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllUsersResponse.ProtoReflect.Descriptor instead.
func (*ListAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_backendservice_backend_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_backendservice_backend_service_proto protoreflect.FileDescriptor

const file_backendservice_backend_service_proto_rawDesc = "" +
	"\n" +
	"$backendservice/backend_service.proto\x12\x0ebackendservice\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x04User\x12\x1a\n" +
	"\bUsername\x18\x01 \x01(\tR\bUsername\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\"B\n" +
	"\x14ListAllUsersResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.backendservice.UserR\x05users2^\n" +
	"\x0eBackendService\x12L\n" +
	"\fListAllUsers\x12\x16.google.protobuf.Empty\x1a$.backendservice.ListAllUsersResponseBfZdgithub.com/adarshhegde/backend-api-repo/proto-files/generated-code/backendservicepb;backendservicepbb\x06proto3"

var (
	file_backendservice_backend_service_proto_rawDescOnce sync.Once
	file_backendservice_backend_service_proto_rawDescData []byte
)

func file_backendservice_backend_service_proto_rawDescGZIP() []byte {
	file_backendservice_backend_service_proto_rawDescOnce.Do(func() {
		file_backendservice_backend_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backendservice_backend_service_proto_rawDesc), len(file_backendservice_backend_service_proto_rawDesc)))
	})
	return file_backendservice_backend_service_proto_rawDescData
}

var file_backendservice_backend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backendservice_backend_service_proto_goTypes = []any{
	(*User)(nil),                 // 0: backendservice.User
	(*ListAllUsersResponse)(nil), // 1: backendservice.ListAllUsersResponse
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
}
var file_backendservice_backend_service_proto_depIdxs = []int32{
	0, // 0: backendservice.ListAllUsersResponse.users:type_name -> backendservice.User
	2, // 1: backendservice.BackendService.ListAllUsers:input_type -> google.protobuf.Empty
	1, // 2: backendservice.BackendService.ListAllUsers:output_type -> backendservice.ListAllUsersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_backendservice_backend_service_proto_init() }
func file_backendservice_backend_service_proto_init() {
	if File_backendservice_backend_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backendservice_backend_service_proto_rawDesc), len(file_backendservice_backend_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backendservice_backend_service_proto_goTypes,
		DependencyIndexes: file_backendservice_backend_service_proto_depIdxs,
		MessageInfos:      file_backendservice_backend_service_proto_msgTypes,
	}.Build()
	File_backendservice_backend_service_proto = out.File
	file_backendservice_backend_service_proto_goTypes = nil
	file_backendservice_backend_service_proto_depIdxs = nil
}
